export type TextVariant =
  | "intro"
  | "subtitle-small"
  | "subtitle-small-bold"
  | "subtitle-large"
  | "body-small"
  | "body-small-bold"
  | "body-large"
  | "body-large-bold"
  | "button"
  | "search"
  | "caption"
  | "caption-large"
  | "overline"
  | "regular";
